# Generated by Django 4.1.5 on 2023-01-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.IntegerField(max_length=122)),
                ('education', models.CharField(max_length=122)),
                ('experience', models.CharField(max_length=122)),
                ('skills', models.CharField(max_length=122)),
            ],
        ),
    ]
