# Generated by Django 4.1.5 on 2023-01-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_form_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
