# Generated by Django 4.1.5 on 2023-01-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_form_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='saveForm',
        ),
    ]
