# Generated by Django 4.1.5 on 2023-01-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_form_saveform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='saveForm',
            new_name='Form',
        ),
    ]
