# Generated by Django 4.1.5 on 2023-01-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_saveform_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
