# Generated by Django 5.0.4 on 2024-11-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0007_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="social_profiles",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files"),
        ),
    ]
